In [ ]:
#LOGISTIC REGRESSION

In [ ]:
#THECLASSIFICATION ALGORITHUM USED TO PREDICT  LOGISTICS REGRESSION ALGORITHUM IS THE BINARY 

In [ ]:
#P=1/1+e-y

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
x=iris.data[:100]
y=iris.target[:100]

In [4]:
x.shape

(100, 4)

In [5]:
import numpy as np

In [6]:
np.unique(y)

array([0, 1])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=10,random_state=1)

In [10]:
x_train.shape

(90, 4)

In [11]:
x_test.shape

(10, 4)

In [12]:
log=LogisticRegression()
log.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
log.intercept_

array([-0.2686235])

In [14]:
log.coef_[0]

array([-0.41681344, -1.41440264,  2.17945356,  0.99789544])

In [15]:
log.score(x_test,y_test)

1.0

In [16]:
log.coef_.shape

(1, 4)

In [17]:
x_test[0]

array([5.5, 2.4, 3.8, 1.1])

In [18]:
def line(x1,x2,x3,x4):
    y=log.intercept_[0]+log.coef_[0][0]*x1+log.coef_[0][1]*x2+log.coef_[0][2]*x3+log.coef_[0][3]*x4
    
    return y
    
    


In [19]:
def prob(x1,x2,x3,x4):
    value=line(x1,x2,x3,x4)
    
    return 1/(1+np.exp(-value))
    

In [20]:
t=x_test[1]

In [21]:
t

array([5.4, 3. , 4.5, 1.5])

In [22]:
prob(t[0],t[1],t[2],t[3])


0.9894576887458335

In [23]:
 line(t[0],t[1],t[2],t[3])

4.5417602007412325

In [24]:
import pandas as pd

In [25]:
data=pd.read_csv