In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd 

In [3]:
vect = CountVectorizer()

In [4]:
messages=['Hey hey hey lets go get lunch today..! ',
         'Did you go home?..',
         'Hey !!! I need a favor']

In [6]:
vect.fit(messages)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [8]:
for i in vect.get_feature_names():
    print (i),

did
favor
get
go
hey
home
lets
lunch
need
today
you


In [11]:
vect.get_feature_names()

['did',
 'favor',
 'get',
 'go',
 'hey',
 'home',
 'lets',
 'lunch',
 'need',
 'today',
 'you']

# there are few things to consider
1 Everything in lowercase
2 Words less than two letter have not been including(ex..'a')
3 Punctuation has been removed
4 there are no duplicates
5 alphabatic order


In [12]:
dtm= vect.transform(messages)

In [15]:
dtm

<3x11 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [19]:
print (dtm.toarray())

[[0 0 1 1 3 0 1 1 0 1 0]
 [1 0 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 1 0 0 0 1 0 0]]


In [16]:
print(dtm)

  (0, 2)	1
  (0, 3)	1
  (0, 4)	3
  (0, 6)	1
  (0, 7)	1
  (0, 9)	1
  (1, 0)	1
  (1, 3)	1
  (1, 5)	1
  (1, 10)	1
  (2, 1)	1
  (2, 4)	1
  (2, 8)	1


In [21]:
df=pd.DataFrame(dtm.toarray(),columns =vect.get_feature_names())

In [23]:
print(df)

   did  favor  get  go  hey  home  lets  lunch  need  today  you
0    0      0    1   1    3     0     1      1     0      1    0
1    1      0    0   1    0     1     0      0     0      0    1
2    0      1    0   0    1     0     0      0     1      0    0
