In [ ]:
#naive bayes classifier
#they data can be use text  base 
#a classification therorm based on bayes's theorm
p(a|b)=p(b|a)p(a)/p(b)

In [1]:
import pandas as pd

In [2]:
#from sklearn.datasets import fetch_20newsgroups

In [4]:
#data=fetch_20newsgroups()

In [5]:
#data.target_names

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [7]:
vect=CountVectorizer()

In [11]:
messages=['Hey hey hey lets go get lunch today..!',
        'Did you go home?..',
        'Hey!!! i need a favor']

In [12]:
vect.fit(messages)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [21]:
print(vect.get_feature_names())

['did', 'favor', 'get', 'go', 'hey', 'home', 'lets', 'lunch', 'need', 'today', 'you']


In [14]:
print(messages[0])

Hey hey hey lets go get lunch today..!


In [15]:
dtm=vect.transform(messages)

In [19]:
#print(dtm)
print(dtm.toarray())

[[0 0 1 1 3 0 1 1 0 1 0]
 [1 0 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 1 0 0 0 1 0 0]]


In [29]:
df=pd.DataFrame(dtm.toarray(),columns=vect.get_feature_names())
print (df)

   did  favor  get  go  hey  home  lets  lunch  need  today  you
0    0      0    1   1    3     0     1      1     0      1    0
1    1      0    0   1    0     1     0      0     0      0    1
2    0      1    0   0    1     0     0      0     1      0    0


In [30]:
test='hello jon..! how are you..?'

In [31]:
messages=['Hello jon ..! how are you..?',
        'Did you go home?..',
        'Hey!!! i need a favor']

In [32]:
vect.fit(messages)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [33]:
print(vect.get_feature_names())

['are', 'did', 'favor', 'go', 'hello', 'hey', 'home', 'how', 'jon', 'need', 'you']


In [34]:
print(messages[0])

Hello jon ..! how are you..?


In [35]:
s="hello jon ..! how are you..?"
print(s)


hello jon ..! how are you..?


In [ ]:
d=['hello','join',]