In [1]:
import numpy as np
a=[1,2,3,4]
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [2]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b[0]

[[1 2 3 4]
 [5 6 7 8]]


array([1, 2, 3, 4])

In [3]:
import numpy as np


In [4]:
#creating array
a=np.array([1,2,3,4])
print (a)
print(type(a))
print(a.ndim)
a.size

[1 2 3 4]
<class 'numpy.ndarray'>
1


4

In [5]:
b=np.array([5,6,7,8])
print(a) 
print (b)


[1 2 3 4]
[5 6 7 8]


In [6]:
v=np.array(['a','b'])
m=np.array(['j','k'])
v[0]


'a'

In [7]:
b=np.array([[1,2,3],[4,5,6]])
print (b)
print (b.ndim)
print( b[1][0])
b.shape
b[1,:2]
b[:,1:]

[[1 2 3]
 [4 5 6]]
2
4


array([[2, 3],
       [5, 6]])

In [8]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (n)
n[:-1]
m=n[:,-1]
m[m!=6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 9])

In [9]:
#print(n[1:,::2][-1::-1])
(n[-1:-3:-1,::2])

array([[7, 9],
       [4, 6]])

In [10]:
#reshape
c=np.array(range(9))
print(c)
p=c.reshape(3,3)
print (p)
print([1])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1]


In [11]:
#resize
c=np.array(range(5))
c.resize(2,4)
print(c)

[[0 1 2 3]
 [4 0 0 0]]


In [12]:
#converted into list
k=np.array([[1,2,3],[4,5,6]],dtype=float)
b=k.tolist()
print(k)
print(b)
print (b,type(b))
#print(c.tolist())
#print(c)
print (c.dtype)
c.astype(np.float64).dtype

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]] <class 'list'>
int32


dtype('float64')

In [13]:
#transpose of an array
p=np.array(range(6)).reshape(2,3)
print(p)
print (p.transpose())

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [14]:
#creating one-dim array from multi-dim.array
r=p.flatten()
print(r)

[0 1 2 3 4 5]


In [15]:
import numpy as np
x=np.array([[1,2],[3,4]],float)
y=np.array([[5,6],[7,8]],float)
print (x)
print(y)
print (x.itemsize)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
8


In [16]:
%%time
p=[]
v=np.empty(10000)
for i,k in enumerate(range(10000)):
    p.append(k**2)


Wall time: 8.01 ms


In [17]:
#in concatenate by default axis=0 row-wise
p=np.concatenate((x,y))
print (p)
print (p.shape)
#print(p.T)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
(4, 2)


In [18]:

print(np.concatenate((x,y),axis=1))

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [19]:
#zeros and ones create array
print(np.ones(3,dtype=int))
#print(np.ones((2,2)))
#print(np.zeros((3,3)))

[1 1 1]


In [20]:
#array()return an array
t=np.arange(1000)
print(t[50:80])
print(np.arange(1,7,2))
#t=t.astype(int)
#print(t) 

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79]
[1 3 5]


In [21]:
#zero and ones create array

print (np.ones(3))
print (np.ones((2,2)))

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [22]:
#the zeros like ones like
#and empty array
#to create an identity matrix(2D array)
print(np.identity (4,dtype=float))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
import numpy as np
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
c[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
c[-1]

array([7, 8, 9])

In [26]:
c[0:2,2]

array([3, 6])

In [27]:
c[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [28]:
f=np.array(range(1,13)).reshape(3,4)
print(f)
x=(f[1,:])
y=(f[1:2,:])
print(x)
print(y)
#print(f[[0,1,2],[0,1,1]])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[[5 6 7 8]]


In [29]:
print (f[[0,1,2],[0,1,1]])

[ 1  6 10]


In [30]:
m=np.arange(6)
m.reshape(2,-1)
print(m.reshape(-1,2))

[[0 1]
 [2 3]
 [4 5]]


In [31]:
m=np.arange(6)
#reshape(1,-1)


In [32]:
f=np.array(range(1,13)).reshape(3,4)
print(f[[0,1,2],[0,1,1]])
b=np.array([0,1])
print(b)
#np.where(n>3)
#print(n[n>3])

[ 1  6 10]
[0 1]


In [33]:
r=np.random.randint(1,6,size=(2,2))
print(r)

[[5 3]
 [1 4]]


In [34]:
c=np.linspace(0,1,10)
#start,end,num points
#including 
print(c)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [35]:
#random numbers
r=np.random.rand(4,2)
print(r)
np.random.random((4,4))

[[0.59426249 0.05612224]
 [0.51279714 0.70217547]
 [0.60022694 0.69275968]
 [0.44355898 0.75621885]]


array([[0.41971898, 0.66253672, 0.68771093, 0.24258359],
       [0.47715883, 0.9913972 , 0.61009704, 0.98013467],
       [0.52358951, 0.44844084, 0.13811623, 0.72616513],
       [0.32288727, 0.6133646 , 0.70961033, 0.76245768]])

In [36]:
import numpy as np
c=np.empty ((2,2))
print(c)

[[5. 6.]
 [7. 8.]]


In [37]:
c[:,:]=np.arange(4).reshape(2,2)
c[:2,:2]=[[2,3],[4,5]]#assigning new value to a empty array
(c)
print(a)
print(np.empty_like(a))

[1 2 3 4]
[0 1 2 3]


In [38]:
np.random.seed(0)
np.random.range(2,2)


AttributeError: module 'numpy.random' has no attribute 'range'

In [ ]:
import numpy as np
x=np.array(10)
print(x)

In [ ]:
#array
x=np.asarray(d)

In [ ]:
import numpy as np
a=np.array([1,2])
b=np.array([1,2])
c=np.array([1,2])
d=[]
d.append(a)
d.append(b)
d.append(c)
print (d)

In [ ]:
x=np.asarray(d)
print (x.shape)
print(x)

In [ ]:
for i in x:
    print (i)
    print (x)

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(np.vstack((x,y)))
np.hstack((x,y))


In [ ]:
#return an array with ones on the diagonal and zero elewhere
n1=np.eye(3,k=2)#no of rows 3
print(n1)
x=np.array([1,2,3,4])
d=np.diag(x)
print(d)

In [ ]:
x=np.array(4)
print(x)